# Generated by Django 5.2.5 on 2026-02-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس URL')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
                'db_table': 'provinces',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='provinces_slug_1152e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس URL')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='location.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
                'db_table': 'cities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس URL')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='location.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'محله',
                'verbose_name_plural': 'محله ها',
                'db_table': 'neighborhoods',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['city'], name='neighborhoo_city_id_95a138_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'name'), name='uniq_neighborhood_name_per_city')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province'], name='cities_provinc_2bfe0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='uniq_city_name_per_province'),
        ),
    ]
