services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/home/app/staticfiles
      - ./media:/home/app/media
    depends_on:
      - django
    networks:
      - agahestan-network

  django:
    container_name: django
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #    command: sh -c "python manage.py migrate &&
    #      python manage.py collectstatic --noinput &&
    #      python manage.py runserver 0.0.0.0:8000"
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      - db
      - redis
    networks:
      - agahestan-network

  db:
    image: postgres:16.9
    container_name: db
    restart: always
    volumes:
      - postgres_data_agahestan:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - agahestan-network

  celery:
    container_name: celery
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --beat -l INFO -Q celery,celery:1,celery:2,celery:3
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      - django
      - redis
      - db
    networks:
      - agahestan-network

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - agahestan-network

networks:
  agahestan-network:
    driver: bridge



volumes:
  postgres_data_agahestan:
