# Generated by Django 5.2.5 on 2026-02-14 12:25

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdReportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='دلیل گزارش')),
            ],
            options={
                'verbose_name': 'دلیل گزارش',
                'verbose_name_plural': 'دلیل های گزارش',
                'db_table': 'ad_report_reasons',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/thumbnails/', verbose_name='thumbnail')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('review', 'در حال بررسی'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده'), ('archived', 'آرشیو'), ('wait_to_pay', 'در انتظار پرداخت')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='طول جغرافیایی')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='قابل مذاکره')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('bumped_at', models.DateTimeField(blank=True, null=True, verbose_name='نردبان/بامپ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('chats_count', models.PositiveIntegerField(default=0, verbose_name='گفت\u200cوگو')),
                ('attributes_cache', models.JSONField(blank=True, null=True, verbose_name='داده \u200cهای کش\u200c شده')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_ads', to='location.city', verbose_name='شهر')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_ads', to='location.neighborhood', verbose_name='محله')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_ads', to='location.province', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
                'db_table': 'ads',
            },
        ),
        migrations.CreateModel(
            name='AdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.ad', verbose_name='آگهی')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='گزارش دهنده')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.adreportreason', verbose_name='دلیل گزارش')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش ها',
                'db_table': 'ad_reports',
            },
        ),
        migrations.CreateModel(
            name='AdViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.ad', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'بازدید آگهی',
                'verbose_name_plural': 'بازدید های آگهی',
                'db_table': 'ad_views',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/icon/', verbose_name='آیکون')),
                ('is_payable', models.BooleanField(default=False, verbose_name='پولی / رایگان')),
                ('is_special', models.BooleanField(default=False, verbose_name='مخصوص')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ad.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ads', to='ad.category', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='کلید')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('type', models.CharField(choices=[('int', 'عدد صحیح'), ('decimal', 'عدد اعشاری'), ('bool', 'درست / نادرست'), ('str', 'رشته متنی کوتاه'), ('text', 'متن بلند'), ('choice', 'انتخابی (لیستی)'), ('multi_choice', 'چندانتخابی')], max_length=20, verbose_name='نوع')),
                ('is_required', models.BooleanField(default=True, verbose_name='فیلد اجباری')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='داده کمکی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'فیلد دسته',
                'verbose_name_plural': 'فیلدهای دسته',
                'db_table': 'category_fields',
            },
        ),
        migrations.CreateModel(
            name='AdAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_attributes', to='ad.ad', verbose_name='آگهی')),
                ('category_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.categoryfield', verbose_name='فیلد دسته بندی')),
            ],
            options={
                'verbose_name': 'مقدار آگهی',
                'verbose_name_plural': 'مقدار آگهی',
                'db_table': 'ad_attributes',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/%Y/%m/%d/', verbose_name='تصویر')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ad.ad', verbose_name='آگهی')),
            ],
            options={
                'verbose_name': 'تصویر آگهی',
                'verbose_name_plural': 'تصاویر آگهی',
                'db_table': 'galleries',
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['uuid'], name='ads_uuid_1cc01e_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['category'], name='ads_categor_89a5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['city'], name='ads_city_id_e6e17b_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['price'], name='ads_price_113b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status'], name='ads_status_6b4e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes_cache'], name='ads_attribu_a38e2b_gin'),
        ),
        migrations.AddIndex(
            model_name='categoryfield',
            index=models.Index(fields=['category'], name='category_fi_categor_5c2292_idx'),
        ),
        migrations.AddIndex(
            model_name='adattribute',
            index=models.Index(fields=['ad', 'category_field'], name='ad_attribut_ad_id_1be950_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adattribute',
            unique_together={('ad', 'category_field')},
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['ad', 'is_main'], name='galleries_ad_id_78afbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('ad', 'is_main'), name='uniq_main_image_per_ad'),
        ),
    ]
