# Generated by Django 5.2.5 on 2026-02-14 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'نشان',
                'verbose_name_plural': 'نشان ها',
                'db_table': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ثبت')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده / نشده')),
            ],
            options={
                'db_table': 'otp',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='نام')),
                ('last_name', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(upload_to='profile/%Y/%m/%d/', verbose_name='نصویر')),
                ('email', models.EmailField(max_length=250, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید')),
                ('temp_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد موقت')),
                ('is_online', models.BooleanField(default=False, verbose_name='آنلاین / آفلاین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'db_table': 'users',
                'indexes': [models.Index(fields=['uuid'], name='users_uuid_4cb658_idx')],
            },
        ),
    ]
