upstream django {
    server django:8000;  # حتماً پورت رو مشخص کن
}

server {
    listen 80;
    client_max_body_size 100M;  # برای آپلود فایل

    # سرویس فایل‌های استاتیک Django
    location /static/ {
        alias /home/app/staticfiles/;
        expires 30d;
    }

    # سرویس فایل‌های مدیا Django
    location /media/ {
        alias /home/app/media/;
        expires 30d;
    }

    location / {
        proxy_pass http://django;  # اینجا نیازی به پورت نیست چون upstream داره
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}